#:schema node_modules/wrangler/config-schema.json
name = "example"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[services]]
binding = "LOCK_MANAGER"
service = "d1-lock-manager"
entrypoint = "LockManager"

[[d1_databases]]
binding = "DB"
database_name = "d1-lock-manager"
database_id = "dummy"
