#:schema node_modules/wrangler/config-schema.json
name = "d1-lock-manager"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "d1-lock-manager"
database_id = "dummy"
